import { StyleSheet,Font } from "@react-pdf/renderer";

export const tableStyles = StyleSheet.create({
    page: {
      display: "flex",
      flexDirection: "column",
      padding: "10px",
      fontFamily: "Helvetica",
    },
    section: {
      marginBottom: "20px",
    },
    table: {
      display: "table",
      width: "100%",
      borderStyle: "solid",
      borderWidth: "1px",
      borderColor: "black",
      borderCollapse: "collapse",
      borderSpacing:0,
      marginBottom: "20px",
    },
    tableHeader: {
      backgroundColor: "#4CAF50",
      color: "#fff",
      textAlign: "center",
      padding: "10px",
      border: "1px solid black",
      borderBottom: "none",
      paddingBottom: "5px",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    tableCell: {
      textAlign: "left",
      paddingLeft: "10px",

      borderLeft: "1px solid black",
     
      borderTop: "1px solid black",
      borderCollapse: "collapse",
      borderSpacing:0,

      paddingBottom: "5px",
    },

    tableCellKelompok: {
      borderLeft: "1px solid black",
      borderLeftColor: "black",
      paddingLeft: "10px",
      paddingBottom: "5px",
      borderCollapse: "collapse",
      borderSpacing:0,
    },

    cellNilai: {
      height: "70px",
      borderLeft: "1px solid black",
      borderBottom: "1px solid black",
      borderColor: "black",
      textAlign: "center",
      borderBottomColor: "black",
      paddingBottom: "5px",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    tableHeaderNoBottomBorder: {
      height: "70px",
      borderBottom: "none",
      borderLeft: "1px solid black",
      borderLeftColor: "black",
      textAlign: "center",
      paddingBottom: "5px",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    tableHeaderNoBottomBorderNo: {
      height: "70px",
      borderBottom: "none",
      borderLeftColor: "black",
      textAlign: "center",
      paddingBottom: "5px",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    cellnoHeight: {
      // borderBottom: "1px solid black",
      height: "40px",
      borderLeft: "1px solid black",
      borderCollapse: "collapse",
      borderSpacing:0,
      borderLeftColor: "black",
      borderBottomColor: "black",
      paddingBottom: "7px",
    },
    noKolom: {
      borderTop: "1px solid black",
      // borderBottom: "1px solid black",
      borderRight: "1px solid black",
      borderColor: "black",
      textAlign: "center",
      paddingBottom: "5px",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    noKolom5: {
      borderTop: "1px solid black",
      borderBottom: "1px solid black",
      borderRight: "1px solid black",
      borderColor: "black",
      textAlign: "center",
      paddingBottom: "5px",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    
    tableCellD: {
      paddingLeft: 10,
      borderTop: "1px solid black",
      borderLeft: "1px solid black",
      borderCollapse: "collapse",
      borderSpacing:0,
      paddingBottom: "5px",
    },
    judulKelompokLeft: {
      borderTop: "1px solid black",
      borderCollapse: "collapse",
      fontWeight:'bold',
      borderSpacing:0,
      textAlign:'left',
    },

    judulKelompok: {
      borderTop: "1px solid black",
      borderLeft: "1px solid black",
      borderCollapse: "collapse",
      borderSpacing:0,
      textAlign:'left',
    },

    noKolomJudul: {
      borderLeft: "1px solid black",
      borderTop: "1px solid black",
      borderBottom: "none",
      borderCollapse: "collapse",
      textAlign:"center",
      borderSpacing:0,
      paddingBottom:"5px",
    },
    noKolomJudul1: {
      // borderLeft: "1px solid black",
      borderTop: "1px solid black",
      borderBottom: "none",
      borderCollapse: "collapse",
      textAlign:"center",
      borderSpacing:0,
      paddingBottom:"5px",
    },

    materiUD: {
      borderTop: "1px solid black",
      paddingBottom: "5px",
      borderCollapse: "collapse",
      borderSpacing:0,
      textAlign:'left'
    },
    materiUDTop: {
      textAlign:'left',
      borderCollapse: "collapse",
      borderSpacing:0,
      paddingBottom: "5px",

    },
    materiUDBottom: {
      borderCollapse: "collapse",
      borderSpacing:0,
      borderBottom: "1px solid black",
      borderTop: "1px solid black",
      textAlign:'left',
      paddingBottom: "5px",

    },
    fullborder: {
      border: "1px solid black",
      borderLeft:"none",
      paddingBottom: "5px",
      textAlign: "center",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    fullBorder: {
      border: "1px solid black",
      paddingBottom: "5px",
      textAlign: "center",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    fullBorder: {
      borderLeft: "1px solid black",
      borderTop: "none",
      paddingBottom: "5px",
      textAlign: "center",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    fullBorder2: {
      textAlign:'left',
      // borderLeft: "1px solid black",
      borderTop: "none",
      paddingBottom: "5px",
      borderCollapse: "collapse",
      borderSpacing:0,
    },
    jumlah: {
      borderLeft: "1px solid black",
      textAlign: "center",
      paddingBottom: "5px",
      borderCollapse:"collapse",
      borderSpacing:0,
      borderSpacing:0,
    },
    nilai:{
      borderLeft: "1px solid black",
      borderTop: "1px solid black",
      paddingBottom: "5px",
    }
  });